base: &base
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PGHOST') { 'db' } %>
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>

development:
  <<: *base
  database: fae_dummy
  host: <%= ENV['DEV_MYSQL_HOST'] || 'localhost' %>

test:
  <<: *base
  database: <%= ENV['MYSQL_DATABASE'] || 'fae_dummy_test' %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['DEV_MYSQL_HOST'] || 'localhost' %>

# There's no remote_development environment
# Keep for reference if we need it
# remote_development:

# Fae Dummy app on Render
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>